import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { GameViewport } from './ui/GameViewport.js';
import { App } from './ui/App.js';
import { SaveConflictGuard } from './ui/SaveConflictGuard.js';
import { I18nProvider } from './i18n/I18n.js';
import { controller } from './runtime.js';
import './pwa.js';
import './ui/styles.css';
import './ui/scene.css';
import './ui/replica-polish.css';
import './ui/airports.css';
import './ui/flight-board.css';
import './ui/railway-inspired.css';
import './ui/railway-inspired-fixes.css';
import './ui/route-dispatch.css';
import './ui/airport-mobile-game-polish.css';
import './ui/airport-mobile-game-polish-fixes.css';
import './ui/art-assets.css';
import './ui/airport-reference.css';
import './ui/airport-mobile-height.css';
import './ui/task-fleet-loading.css';
import './ui/viewport.css';
import './ui/start-screen.css';
import './ui/navigation.css';
createRoot(document.getElementById('root')!).render(<StrictMode><I18nProvider><GameViewport><App /><SaveConflictGuard /></GameViewport></I18nProvider></StrictMode>);
void controller.start();
