import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './ui/App.js';
import { SaveConflictGuard } from './ui/SaveConflictGuard.js';
import { controller } from './runtime.js';
import './pwa.js';
import './ui/styles.css';
import './ui/scene.css';
import './ui/replica-polish.css';
import './ui/airports.css';
createRoot(document.getElementById('root')!).render(<StrictMode><App /><SaveConflictGuard /></StrictMode>);
void controller.start();
